### ISSUE TITLE
Turn on tslint:all so we are strict

### ISSUE THREAD

**Issue by benmatselby** [emisgroup/vsts-dashboard#29]
This helps identify issues, and therefore should be `all` instead of `recommended`

**Comment by benmatselby** [comment]
#25 fixed a lot of issues and I wanted these merged in, so I reset back to `recommended` so we could merge, but will leave this issue open, so we can keep making progress

**Comment by MarkGaze** [comment]
#63 will get us a bit closer to this 😄

**Comment by benmatselby** [comment]
Mark and I have now reviewed what is defined and are happy with that list for now.. We can review on a case by case basis in future if the need arises.
