### ISSUE TITLE
Config page is not responsive

### ISSUE THREAD

**Issue by MarkGaze** [emisgroup/vsts-dashboard#53]
When using the settings page on a smaller screen, the input fields don't look great as they get wrapped around

**Comment by benmatselby** [comment]
<img width="501" alt="screen shot 2018-06-03 at 14 25 38" src="https://user-images.githubusercontent.com/178634/40887028-066ef1cc-673a-11e8-90f3-1fde13408d1e.png">
<img width="256" alt="screen shot 2018-06-03 at 14 25 29" src="https://user-images.githubusercontent.com/178634/40887029-06884f5a-673a-11e8-8967-825d7ee90fd2.png">


Closing this now as the config page looks responsive to me.. The version number could do with moving, but will look at that separately, as not related to this ticket
