### ISSUE TITLE
README suggests that the access token only needs "Code (read)" but this doesn't appear to be the case

### ISSUE THREAD

**Issue by MarkGaze** [emisgroup/vsts-dashboard#58]
The README states that the VSTS access token only needs "Code (read)" but this hasn't worked for a few people, we need to find out the correct rights that the token needs and update the README

**Comment by benmatselby** [comment]
My token only has this so I wonder if it’s then account related as me and you are both admins?

I’ll pick this up when I’m back if no one else has time

**Comment by MarkGaze** [comment]
I was thinking something similar but then I don't think the CI user on the TV is an admin?

**Comment by benmatselby** [comment]
Have a chat with Ben D because we did do something to that account actually

**Comment by benmatselby** [comment]
The token for the TV does only have code read as I didn’t want an unattended privileged token being used :-)
