### ISSUE TITLE
VSTS Dashboard not updating build Status until we refresh the page.

### ISSUE THREAD

**Issue by aravindkumaremis** [emisgroup/vsts-dashboard#70]
I have submitted a branch for build and I can see the build progress in VSTS Dashboard, But once the build finished, it's not updated the Board. I manually refreshed the dashboard to see the result.  Will Check again and try to share screenshots.

**Comment by MarkGaze** [comment]
Linked to #57

**Comment by benmatselby** [comment]
Mark and I have reviewed this item, and will close as a duplicate of #57.. Please follow #57 for further updates @aravindkumaremis. Thank you very much for raising this.
