### ISSUE TITLE
Get Docker to build the image and push on every commit to master

### ISSUE THREAD

**Issue by benmatselby** [emisgroup/vsts-dashboard#71]
We should setup the docker hub build system for this repo

**Comment by MarkGaze** [comment]
Can we get it to push to :latest every commit and a tagged version when we tag the repo?

**Comment by benmatselby** [comment]
Yes, this is all part of the build settings in Docker.. This should be a fairly easy one to knock off to be honest.. We let Circle CI run the build, and on merge to master in GitHub, Docker will track the master branch and then build for us there.
