### ISSUE TITLE
Dashboard doesn't alert when the project is not found

### ISSUE THREAD

**Issue by MarkGaze** [emisgroup/vsts-dashboard#8]
When the environment variables are set to a project that does not exist in VSTS then the dashboard just sits there loading endlessly.

The developer console shows that a 400 error is returned so we need to react to this.

**Comment by benmatselby** [comment]
@MarkGaze I've been thinking as to whether the initial screen should actually shows the list of projects for the account, meaning we can take an environment variable out of the picture and allow the user to pick which project to display.. This means you can run the same docker container for multiple projects within a team

Maybe this could feed into this issue?

**Comment by MarkGaze** [comment]
Sounds good to me, we could potentially use some routing to have static URLs that we can go directly to but the "home page" would be the selection screen?

**Comment by MarkGaze** [comment]
Talking of getting rid of environment variables, I've just found this https://github.com/AzureAD/azure-activedirectory-library-for-nodejs

I _think_ we could use this to authenticate rather than using a token so then we'd just need a way of configuring the VSTS account

**Comment by MarkGaze** [comment]
Potential handling of this:

![image](https://user-images.githubusercontent.com/16718355/41025183-26180cb2-6969-11e8-876e-908f91b410be.png)

Thoughts @benmatselby?
